model_params:
  model: ZindiModel
  model_name: resnet18
  pretrained: True

args:
  expdir: "./src"
  logdir: "./logdir"
  
runner_params:
  input_key: "images"
  output_key: "logits"
  input_target_key: "targets"

distributed_params:
  opt_level: O1

stages:

  data_params:
    num_workers: 8
    batch_size: 16
    per_gpu_scaling: True
    img_folder: './input/train_clean'
    train_csv: './folds.csv'
    test_fold_number: 0
    tile:
      height: 1
      width: 1
      splitter_width: 0
      always_apply: True
      p: 1.
      
  state_params:
    main_metric: logloss
    minimize_metric: True

  criterion_params:
    _key_value: True
    ce:
      criterion: CrossEntropyLoss

  callbacks_params:
    loss:
      callback: CriterionCallback
      input_key: targets
      output_key: logits
      criterion_key: 'ce'
      prefix: 'loss'

    optimizer:
      callback: OptimizerCallback
    saver:
      callback: CheckpointCallback
    metric:
      callback: LogLoss

  stage1:
    state_params:
      num_epochs: 30
      
    scheduler_params:
      scheduler: OneCycleLRWithWarmup
      num_steps: 500
      warmup_steps: 5
      lr_range: [0.012, 0.0001]
      momentum_range: [0.85, 0.99]

    optimizer_params:
      optimizer: AdamW
      lr: 0.00001
      
    transform_params:
      _key_value: True
      train:
        transform: A.Compose
        transforms:
          - transform: A.LongestMaxSize
            max_size: 256
          - transform: A.HorizontalFlip
          - transform: A.VerticalFlip
          - transform: A.RandomBrightnessContrast
          - transform: A.ShiftScaleRotate
          - transform: A.PadIfNeeded
            min_height: 256
            min_width: 256
          - transform: A.Cutout
            num_holes: 16
            max_h_size: 16
            max_w_size: 16
      valid:
        transform: A.Compose
        transforms:
          - transform: A.LongestMaxSize
            max_size: 256
          - transform: A.PadIfNeeded
            min_height: 256
            min_width: 256
